language: python

sudo: false

python:
  - '2.7'

install:
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
- COMPILE='--compile' make test
