language: python

sudo: false

python:
  - '3.5'
  - '2.7.11'
  - '2.6'
  - '3.4'
  - 'pypy'

install:
- |
    if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
      export PYENV_ROOT="$HOME/.pyenv"
      if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
        pushd "$PYENV_ROOT" && git pull && popd
      else
        rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      export PYPY_VERSION="5.3"
      "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
      virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
      source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
    fi
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check

# blacklist
branches:
  except:
    - data-driven-pytest
